ammarhakim/gkeyll

regression/rt_mhd_brio_wu.c
regression/rt_mhd_ot.c
regression/rt_mhd_rj2.c
unit/ctest_wv_mhd.c
zero/gkyl_prim_mhd.h
zero/gkyl_wv_mhd.h
zero/prim_mhd.c
zero/wv_mhd.c

I might have to stop working on this for now so I'm saving the updates.
- Dedner's GLM scheme for div(B) cleaning. Only the hyperbolic part is implemented.
- 1d 7-wave test of Ryu & Jones (1995)
- 2d Orszag-Tang test using GLM-MHD.
- Even without the damping term, GLM seems to give OK results but the run still dies due to negative pressure/density. In contrast, without any cleaning, the results seem incorrect after a while.
- Source term for the div(B) damping in GLM-MHD.
- For GLM, right now, the propagation speed is set to the fast magnetosonic speed. It could be `cfl * dx / dt`.
The GLM div(B) waves are added on top of the ideal MHD roe solver. This does NOT yield a roe solver for the full 9-wave system that satisfies `fr-fl=amdq+apdq`. This is because the (Bx, psi) system is evolved …

MHD GLM div(B) cleaning work-in-progress before pausing the hackweek

---

unit/ctest_array.c
zero/array_ops.c
zero/array_ops_cu.cu
zero/gkyl_array_ops.h

method to shift the 0th component of an array by a constant.
This is intended for shifting DG fields by some constant. The user needs to make sure the normalization of the constant is computed correctly.
unit tests pass on CPU & GPU

Array shiftc0

---

apps/gkyl_vlasov.h
apps/gkyl_vlasov_priv.h
apps/vm_field.c
apps/vm_fluid_species.c
apps/vm_species.c
regression/rt_mirror_lorentzian_1x1v_p_perp.c
zero/bc_basic.c
zero/bc_basic_cu.cu
zero/dg_maxwell.c
zero/dg_maxwell_cu.cu
zero/gkyl_bc_basic.h
zero/gkyl_bc_basic_priv.h
zero/gkyl_dg_maxwell.h
zero/gkyl_dg_maxwell_priv.h

This branch puts copy BCs and Maxwell's equations perfect electrical conductor BC. Also cleans up the G0 app significantly now that all currently supported BCs (across Vlasov, fluids, and Maxwell's) are handled through bc_basic.

Add more boundary conditions to bc_basic for G0-G2 merge

---

zero/gkyl_mom_calc_bcorr.h
zero/mom_calc_bcorr.c
zero/mom_calc_bcorr_cu.cu
zero/prim_lbo_calc.c

This branch returns mom_calc_bcorr to its originally functionality of looping over edges in velocity space since ghost_surf_calc handles the more general case of computing fluxes at edges of the domain. 
Equally important: the derived constructor classes had memory leaks because they were creating types (mom_type or prim_lbo_type) and then creating the calculators which call acquire methods on these types.
As such, since we do not need the specific types subsequently after the calculator construction has acquired a pointer to these types, we call the release methods on these specific types. This decreases the reference count from 2 -> 1 (it goes from 1 -> 2 when the calculator calls the acquire) so that when the release method is called on the calculator at the end of the simulation, the …

Clean up of mom_calc_bcorr and fix memory leaks

---

unit/ctest_proj_maxwellian_on_basis.c
zero/gkyl_proj_maxwellian_on_basis.h
zero/gkyl_proj_maxwellian_on_basis_priv.h
zero/proj_maxwellian_on_basis.c
zero/proj_maxwellian_on_basis_cu.cu

GPU implementation of proj_maxwellian_on_basis.
This also implements the methods in this updater to project a maxwellian using the primitive moments m0, u and vtsq, which is more convenient for neutral models.
Note: unit tests pass on CPU and GPU. But when you run it with valgrind it seems to run to completion without errors but it crashes with a ```Test interrupted by SIGILL.``` message.

GPU implementation of MOB

---

unit/ctest_basis.c
unit/ctest_proj_maxwellian_on_basis.c
zero/cart_modal_gkhybrid.c
zero/cart_modal_gkhybrid_cu.cu
zero/cart_modal_hybrid.c
zero/cart_modal_hybrid_cu.cu
zero/cart_modal_serendip.c
zero/cart_modal_serendip_cu.cu
zero/cart_modal_tensor.c
zero/gkyl_basis.h
zero/proj_maxwellian_on_basis_cu.cu

Add _new methods to the basis objects to allocate and assign basis objects. See commit message.
This means that basis objects will have to be freed with gkyl_free or gkyl_cu_free. I didn't add a release method for basis because the release is simply gkyl_free/gkyl_cu_free. But thinking about g2, maybe a release method is necessary so that g2 doesn't have to choose between gkyl_free or gkyl_cu_free, (g0 would make that choice based on where the basis is allocated).
Basis unit test pass on CPU and GPU, and rt_sheath_1v test looks identical before and after this change.
Also: I caught an error in proj_maxwellian_on_basis prim_mom methods which I fixed in this branch.

Implement _new basis methods for creating basis objects

---

apps/gkyl_vlasov_priv.h
apps/vlasov.c
apps/vm_species.c
apps/vm_species_source.c

- Fixed a number of memory issues with the source/boundary flux implementation.
- Previously the source set a flag for the source species telling it to do the boundary flux as part of its RHS update. In addition to causing issues where flags are being set for uninitialized species, it is preferable to not have species sub-objects setting flags for a separate species.
- To clean up this process, the source update was moved outside the species RHS function, and the boundary flux calculation for the source species is handled entirely inside the source object that points to it.

VM Source Cleanup

---

regression/rt_mhd_brio_wu.c
regression/rt_mhd_ot.c
regression/rt_mhd_rj2.c
zero/gkyl_wv_mhd.h
zero/wv_mhd.c

- fixed typo in OT initial condition; taken from https://www.astro.princeton.edu/~jstone/Athena/tests/orszag-tang/pagesource.html
- encapsulate initialization parameters
TODO:
- Dedner's GLM: implement and test different choices of ch. Following are used for now
```c
if (mhd->glm_ch > 0)
ch = mhd->glm_ch;
else
// candidates:
// 1. Dedner (2002) sec 4: cfl * min(dx, dy, dz) / dt
// 2. Derigs (2018) eq 3.30: max_speed_global - max_global(|u|, |v|, |w|)
// 3. local version of 2; needs to store ch for the source step
ch = max_speed;
```

Minor cleanup of mhd solver to prepare for the mhd source solver

---

zero/prim_lbo_gyrokinetic_cu.cu

Forgot to do this in previous commits. Cross GkLBO runs on GPUs now and results are essentially identical to CPU results.

Set cross prim mom kernels for GkLBO on device

---

unit/ctest_array.c
zero/array_ops.c
zero/array_ops_cu.cu
zero/gkyl_array_ops.h

Implement offset methods we had in g2. These do the same as _set and _accumulate, but take the extra ```coff``` (offset) argument to indicate a (DG) component offset. This allows us to do operations with/on a specific component of a vector field.
Make check passes. CPU and GPU tests for these methods are implemented and pass.

Offset array methods

---

zero/dg_lbo_gyrokinetic_diff.c
zero/dg_lbo_gyrokinetic_diff_cu.cu
zero/dg_lbo_gyrokinetic_drag.c
zero/dg_lbo_gyrokinetic_drag_cu.cu
zero/dg_lbo_vlasov_diff.c
zero/dg_lbo_vlasov_diff_cu.cu
zero/dg_lbo_vlasov_drag.c
zero/dg_lbo_vlasov_drag_cu.cu
zero/dg_updater_lbo_gyrokinetic.c
zero/dg_updater_lbo_vlasov.c
zero/gkyl_dg_lbo_gyrokinetic_diff.h
zero/gkyl_dg_lbo_gyrokinetic_diff_priv.h
zero/gkyl_dg_lbo_gyrokinetic_drag.h
zero/gkyl_dg_lbo_gyrokinetic_drag_priv.h
zero/gkyl_dg_lbo_vlasov_diff.h
zero/gkyl_dg_lbo_vlasov_diff_priv.h
zero/gkyl_dg_lbo_vlasov_drag.h
zero/gkyl_dg_lbo_vlasov_drag_priv.h

Under certain circumstances the LBO cross primitive moments, u and vtSq, can acquire unreasonable results, like
u > v_max
vtSq < 0
vtSq > v_max^2
Add if-statements in the LBO equation objects so that in these cases we turn the LBO off. We had this in g2 and it may improve stability. 
In g2 we did two more things:
- We kept track of how often the LBO gets turned off.
- We also turned the LBO off if M2<0.
at some point we should implement these in g0 as well, but for now I want to check if these are sufficient to get rid of some numerical instabilities.

LBO checks

---

zero/dg_lbo_gyrokinetic_diff.c
zero/dg_lbo_gyrokinetic_diff_cu.cu
zero/dg_lbo_gyrokinetic_drag.c
zero/dg_lbo_gyrokinetic_drag_cu.cu
zero/dg_updater_lbo_gyrokinetic.c
zero/gkyl_dg_lbo_gyrokinetic_diff.h
zero/gkyl_dg_lbo_gyrokinetic_diff_priv.h
zero/gkyl_dg_lbo_gyrokinetic_drag.h
zero/gkyl_dg_lbo_gyrokinetic_drag_priv.h
zero/gkyl_dg_updater_lbo_gyrokinetic.h

We had this check in g2.
I've done at least 1 simulation (1x2v p1, hot electron LTX case with constant B, showing unphysical oscillations at the boundaries) which used to run in g2 (although I later found an important error in the initial condition of the g2 simulation) but now crashes in g0-g2. After adding this check on M2, the simulation appears to run longer.
I think is is a temporary bandaid, and as @JunoRavin said in another PR (or private comm), perhaps a simulation that incurs in this M2<0 scenario should be discarded. I still think it is useful to keep a simulation that may have some negativity, but the result should be examined critically (for which we need more diagnostics), and it is certainly the case here that the result is unphysical (i.e. oscillatory near the sheath). …

Add a M2>0 check to GkLBO. Turn off if false.

---

unit/README.md
unit/ctest_proj_powsqrt_on_basis.c
unit/ctest_spitzer_coll_freq.c
zero/gkyl_proj_powsqrt_on_basis.h
zero/gkyl_proj_powsqrt_on_basis_priv.h
zero/gkyl_spitzer_coll_freq.h
zero/gkyl_spitzer_coll_freq_priv.h
zero/proj_powsqrt_on_basis.c
zero/proj_powsqrt_on_basis_cu.cu
zero/spitzer_coll_freq.c
zero/spitzer_coll_freq_cu.cu

Implement updaters that compute the Spitzer collision frequency and pow(sqrt(f),q) using Gaussian quadrature.
Spitzer_coll_freq currently only has the normNu option, since I think that's the most useful right now.
Unit tests pass on the CPU and GPU. However valgrind is giving errors on the ```qrange``` function in these updaters, but that is the exact same function as in proj_maxwellian_on_basis, so I don't know if it's a true error. Maybe reviewers can check in another (non-stellar) computer.

Spitzer and pow(sqrt()) updaters

---

zero/wv_maxwell.c

This is an issue with many complicated problems in which the EM field has all terms active. I have to revert back to the pre-MP-XX qfluct till I figure out why the Maxima generated code is not working.
Maxwell MP-XX will NOT WORK at present. Need to figure this out slowly and properly.

Fixing a problem with Maxwell eqn qfluct. This seems to be a serious issue!

---

Makefile
configure
install-deps/build-openblas.sh
install-deps/build-superlu.sh
machines/configure.perlmutter.dev.sh
machines/mkdeps.perlmutter.dev.sh
zero/array_ops.c
zero/bc_basic.c
zero/gkyl_array_ops.h
zero/prim_lbo_cross_calc.c

default. That's because currently those executables take way too much space and if you have other stuff in your $HOME, your diskspace can easily fill up and crash the build. Now one has to build these on demand with, for example,
make cuda-build/regression
make cuda-build/unit
or specific tests with
make cuda-build/regression/rt_weibel_4d
make cuda-build/unit/ctest_dg_bin_ops
Additionally, change ```-j``` in scripts that build dependencies to
```-j 32``` because Stellar and Perlmutter admins don't like that we hog
all the cores on the login node.
Adapt config and make files to allow passing location of cuda math
libraries, because on Perlmutter they are in some other nonstandard
location. Update Perlmutter machine files with this (also had to unload
darshan module for some reason, …

Change Makefile so /regression and /unit executables are not built by

---

zero/wave_prop.c
zero/wv_euler.c
zero/wv_mhd.c

- `euler` and `mhd` lax solvers now use two waves, and they are computed in their `wave` functions, not `qfluct` functions.
- The primary motivation is to ensure the speeds in `wave` and `qfluct` are consistently re-scaled on a mapped grid.
- The implementation really is just HLL with left and right speeds `sl=-sr`.
- IMO, Lax is a two-wave scheme instead of a single-wave scheme as it has simultaneously nonzero `amdq` and `apdq`. A one-wave scheme would give unwinding with `sl` or `sr` set to zero.
- The lax results seem unaffected if no second-order correction is applied.

wave prop scheme: use two waves for lax solver

---

Makefile

e.g., `make BUILD_DIR=build002` will make `build002/libgkylzero.so`
Then one may create multiple builds under the same `gkylzero` folder.

Makefile: allow setting BUILD_DIR

---

Makefile
Makefile.sample
configure
zero/wave_prop.c
zero/wv_euler.c
zero/wv_mhd.c

This branch has two unrelated work:
- Makefile mods to only build shared library. So static lib is not build any more. All unit and regression tests use shared libs only. Leads to dramatic reduction in disk space: 10 GB -> 8 MB for nvcc builds. Of course, builds are still taking long.
- Liang's fixed to Euler Lax solver to use two waves rather than 1. Added consistency to the speeds used in the Lax fluxes which were previously unscaled.

Makefile fixes and some FV mods 

---

zero/wave_geom.c

***Preparing*** to support custom grids that cannot be computed from a `mapc2p` function. A custom grid would contain pre-computed physical coordinates of all nodes.

Split the physical coordinte computation and geometry metric computation

---

unit/ctest_correct_maxwellian.c
unit/ctest_proj_maxwellian_on_basis.c
zero/bgk_collisions.c
zero/bgk_collisions_cu.cu
zero/gkyl_bgk_collisions.h
zero/gkyl_bgk_collisions_priv.h
zero/gkyl_prim_cross_m0deltas.h
zero/gkyl_prim_cross_m0deltas_priv.h
zero/gkyl_proj_maxwellian_on_basis.h
zero/gkyl_proj_maxwellian_on_basis_priv.h
zero/prim_cross_m0deltas.c
zero/prim_cross_m0deltas_cu.cu
zero/proj_maxwellian_on_basis.c
zero/proj_maxwellian_on_basis_cu.cu

Primarily implement three things:
1. Projection of a GK Maxwellian onto the basis using quadrature, lab_mom and prim_mom versions. This is used during initialization, BGK collisions and neutral interactions.
2. BGK operator.
3. An updater which computes the prefactor M_0s*delta_s appearing in cross primitive moments (previously we did it with a series of binOps).
All are implemented for GPUs too, and all are wrapped and tested via g2.

Project maxwellian, BGK and LBO cross prim mom prefactor

---

zero/gkyl_prim_bgk_cross_calc.h
zero/gkyl_prim_cross_m0deltas.h
zero/gkyl_prim_cross_m0deltas_priv.h
zero/prim_bgk_cross_calc.c
zero/prim_bgk_cross_calc_cu.cu
zero/prim_cross_m0deltas.c
zero/prim_cross_m0deltas_cu.cu
zero/proj_maxwellian_on_basis.c

(continuation of pull request #123 )
Change the signature of the updater that computes the m0_s*delta_s prefactor for LBO cross-species collisions so it works with BGK as well (i.e. only compute delta_s for BGK).
Implement a function to compute BGK cross-primitive moments, CPU and GPU.
Tested via g2. Cross BGK reg tests pass on CPU (compared to results created with g2's old CrossPrimMom for BGK). Also,  cross BGK now runs on GPU and produces identical (to machine precision) results to those on CPU.

Cross BGK prim moms (+ some edits for LBO too)

---

unit/ctest_mom_gyrokinetic.c
unit/ctest_spitzer_coll_freq.c
zero/dg_updater_gyrokinetic.c
zero/gkyl_dg_updater_gyrokinetic.h
zero/gkyl_dg_updater_gyrokinetic_priv.h
zero/gkyl_spitzer_coll_freq.h
zero/gkyl_spitzer_coll_freq_priv.h
zero/spitzer_coll_freq.c
zero/spitzer_coll_freq_cu.cu

- Create a gyrokinetic updater which wraps hyper_dg and the GK equation object. Tested via g2.
- Implement option in the Spitzer collisionality updater to build the collision frequency from scratch (not normNu), and make other minor changes to normNu.
At first I tried to run the GK 1x2v-p1 sheath test with normNu, and I encountered issues of variable results on the GPU or GPU results that don't match the CPU results. This is still the case. However at higher resolution (2X in all dimensions) those problems go away. I don't understand why the coarse grid behavior is so erratic. It improves if moments and primitive are computed on the CPU. I implemented GPU unit tests for GK moments and didn't find errors though.
Somewhat unsatisfactory but I'm afraid this will have to do for now.

Gyrokinetic updater and additions to Spitzer collisionality updater

---

apps/gkyl_moment.h
apps/gkyl_moment_priv.h
apps/mom_coupling.c
apps/mom_priv.c
apps/mom_species.c
apps/moment.c
regression/rt_10m_burch_grad_closure.c
regression/rt_10m_gem_grad_closure.c
regression/rt_10m_lhdi.c
regression/rt_10m_lhdi_grad_closure.c
regression/rt_10m_par_firehose_grad_closure.c
zero/gkyl_moment_em_coupling.h
zero/gkyl_moment_non_ideal_priv.h
zero/gkyl_ten_moment_grad_closure.h
zero/gkyl_util.h
zero/moment_em_coupling.c
zero/ten_moment_grad_closure.c

We have had a functional gradient-based closure in 10 moment in at least 2 different branches but we have never merged it into main because we were always doing additional development work in those branches. 
I have adapted the gradient-based closure to be functional in the current version of main by just adding an additional RHS term to the pressure before it's rotated around the magnetic field (i.e., treating div(q) as an explicit source in the time integration).
In the long term we will want to split the non-ideal terms out from the source solve (or make the source solve do another operator split to treat these types of dissipative terms). But the gradient-based closure is very mature (especially compared to Braginskii) and people want to use it, so let's get this functionality in …

Merge grad closure

---

Makefile

Due to an issue with shared-lib linking on the Mac, we need to build
a separate shared lib to install. This one has the install path
hard-coded into the library itself, so external execs, like gkyl,
can link to the library properly. Perhaps there is a another way to
do this, don't know. .

Now building two shared libs on Mac to get around link issues

---

apps/gkyl_moment.h
apps/gkyl_moment_priv.h
apps/mom_coupling.c
apps/moment.c
unit/ctest_mat.c
zero/gkyl_mat.h
zero/gkyl_moment_em_coupling.h
zero/moment_em_coupling.c

Adapt Pull Request #122 which was closed without merging.
Gkyl side change: https://github.com/ammarhakim/gkyl/pull/115
That PR was used in a bunch of tests but this new PR has not been extensively tested (though it does not break anything).
During the simulation, one has   `nu_sr=base*rho_r` and   `nu_rs=base*rho_s` to satisfy
`nu_sr*rho_s=nu_rs*rho_r=base*rho_s*rho_r`.
struct gkyl_moment app_inp = {
// ...
.has_collision = true,
// scaling factors for collision frequencies;
// the matrix must be symmetric;
.nu_base =
{
{0,          0,          nu_base_en}, // ee, ei, en
{0,          0,          nu_base_in}, // ie, ii, in
{nu_base_en, nu_base_in, 0         }  // ne, ni, nn
},
}

Collisions between 5-moment fluid species

---

apps/gkyl_app.h
apps/gkyl_moment.h
apps/mom_field.c
apps/mom_species.c
inf/Moments.lua

Associated G2's g0-merge PR: https://github.com/ammarhakim/gkyl/pull/117
Usage example in c:
```c
void bcx_lower_func(
double t, int nc, const double *skin, double * GKYL_RESTRICT ghost, void *ctx)
{
for (int c=0; c<8; ++c)
ghost[c] = skin[c];
}
// ...
struct gkyl_moment app_inp = {
// ...
.field = {
// ...
.bcx = { GKYL_FIELD_FUNC, GKYL_FIELD_PEC_WALL },
.bcx_lower_func = bcx_lower_func,
},
// ...
};
```
Usage example in lua:
```lua
function bc_upper_func(t, nc, skin, ctx)
return rhoIn, rhoIn*uIn, 0.0, 0.0, erIn
end
fluid = Moments.Species {
-- ...
bcx = { Moments.Species.bcCopy, Moments.Species.bcFunc},
bcx_upper_func = bc_upper_func,
-- ...
}
```

Moments: FUNC boundary conditions for fluid species and field

---

apps/gkyl_moment.h
apps/moment.c

Following code would give an error:
```lua
vm.low_inp.local = grid._localRange
```
The following is OK:
```lua
vm.low_inp.local_range = grid._localRange
```

rename local to local_range to avoid syntax error when set from lua

---

kernels/lbo/gkyl_mom_bcorr_lbo_gyrokinetic_kernels.h
kernels/lbo/gkyl_mom_bcorr_lbo_vlasov_kernels.h
kernels/pkpm/gkyl_mom_bcorr_lbo_vlasov_pkpm_kernels.h
zero/array_rio.c
zero/dynvec.c
zero/gkyl_elem_type.h
zero/gkyl_elem_type_priv.h
zero/gkyl_eqn_type.h
zero/gkyl_mom_calc_bcorr.h
zero/mpi_comm.c
zero/null_comm.c

gkyl_elem_type.h had some C-safe syntax that was not C++ safe. This would normally not matter except gkyl_elem_type.h was being included in a few places that were being compiled as CUDA kernels through some unsafe header proliferation.
We have split out the parts of gkyl_elem_type.h that C++ does not like into a private header that is included in the necessary C files that nvcc compiles with the host compiler and also fixed the header for the offending code in the kernels by moving the gkyl_vel_edge enum out of gkyl_mom_calc_bcorr.h into gkyl_eqn_type.h, the latter being a header file of exclusively enums that is safe to include in these places.

Fix CUDA build

---

unit/ctest_correct_mj_integrated.c
zero/correct_mj.c

- Fixed bug in correct_mj algorithm which was preventing the 3V case from properly converging
- Changed the iterative scheme to terminate if certain tolerances on convergence are met. This significantly reduces the computations required in most cases.

Improved correct_mj iteration efficiency and accuracy

---

machines/configure.perlmutter.dev.sh

version 22.5 no longer exists. switching it for 22.7 works.

Fixing CUDAMATH_LIBDIR in perlmutter configure

---

Makefile
configure
machines/configure.perlmutter.dev.sh
machines/configure.stellar.dev.sh
machines/configure.stellar.host.sh
machines/mkdeps.stellar.host.sh

Previously installing gkyl in a different directory required more changes. Now, with this change, the user just has to change PREFIX and GKYLSOFT in the machine files.

Remove harcoded $HOME in build files

---

unit/ctest_array.c
zero/array_rio.c

This was incorrectly setting the elem-type of the data in the array. Of course, this was the one thing with no unit tests and so it is not surpizing it had a bug.

Fixed a bug in the read function

---

unit/mctest_mpi_comm.c
zero/gkyl_comm.h
zero/mpi_comm.c

Add functions that allow us to send and recv whole gkyl_arrays. This is intended to send moments across the species communicator. Also add a method to split a gkyl_comm. However, I have some doubts as to what precise flow we wish people to follow to create other gkyl_comm objects. There are two options (only option 1 is implemented here):
1. Use gkyl_comm_split_comm, which takes in a parent gkyl_comm, a color, and a decomp. This calls MPI_Comm_split inside.
2. Call MPI_Comm_split to get a new MPI_Comm, then pass that to gkyl_mpi_comm_new.
Submitting this PR for review to hear comments on this structure.

Enhance mpi_comm object with ability to send/recv gkyl_arrays, and split a comm

---

zero/fem_poisson.c
zero/fem_poisson_perp.c
zero/superlu_ops.c

There were some memory leaks and misallocated arrays in fem_poisson and superlu_ops. These are fixed. The fem_poisson unit tests are now fully valgrind clean! All is good with the world again.

Fixed memory leaks in fem_poisson

---

zero/gkyl_dg_diffusion_fluid_priv.h
zero/gkyl_dg_diffusion_gyrokinetic_priv.h
zero/gkyl_dg_diffusion_vlasov_priv.h

specified bound between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
in GPU builds with CUDA 12. Changing to int since these are small loops, which removes the warning.

Use of size_t causes an ominous warning: 

---

apps/mom_coupling.c
regression/rt_10m_par_firehose.c
regression/rt_10m_par_firehose_grad_closure.c

Via some testing this weekend, I realized that the gradient-based closure was not actually parallelized, defaulting to always looping over the global range ro compute the heat flux, even if the local range for the app was still utilized to construct the final update to the pressure.
In the process I realized this whole time the gradient-based closure had a significant error: the non-ideal variable range wasn't actually being used for updating the pressure tensor, so the div(q) was wrong in the final right-most cell. This error of course affects simulations performed, though perhaps only quantitatively and not qualitatively (the parallel firehose run still grows a mode with basically the same wavelength). More testing is required.
For right now, I use the create_ranges method from …

Fix of gradient-based closure: now parallelized and correct ranges. 

---

unit/ctest_array_integrate.c
zero/array_integrate.c
zero/array_integrate_cu.cu
zero/gkyl_array_integrate.h
zero/gkyl_array_integrate_priv.h
zero/gkyl_bc_sheath_gyrokinetic.h

This operator integrates a gkyl_array performing some simple operations within the integral (e.g. none, abs, sq). This is similar to what CartFieldIntegratedQuantCalc did in g2 and will be wrapped by such.

Array integrate operator

---

Makefile
kernels/array_integrate/array_integrate_op_int.c
kernels/array_integrate/gkyl_array_integrate_kernels.h
unit/ctest_array_integrate.c
zero/array_integrate.c
zero/array_integrate_cu.cu
zero/array_ops_cu.cu
zero/gkyl_array_integrate.h
zero/gkyl_array_integrate_priv.h

(goes with gkylcas PR 28: https://github.com/ammarhakim/gkylcas/pull/28)
In order to incorporate this additional operator we extended array_integrate by adding support for a (gkyl_array) weight. I also moved the kernels to a new kernel folder. Unit tests still pass on CPU and GPU.

Extend array integrate to include eps_gradperp_sq needed for GK

---

zero/gkyl_wv_eqn.h

Adding `static` to all `inline` functions in the wv_eqn header. This was causing some compilation issues; for example, it was impossible to build the regression tests on Linux without the optimization, i.e. with `-O0`

Adding 'static' to inline functions

---

apps/mom_coupling.c
apps/mom_priv.c
zero/gkyl_moment_non_ideal_priv.h
zero/ten_moment_grad_closure.c

The main change is in the `ten_moment_grad_closure_advance` method; there the `update_range` was used to calculate the `offsets_centers` and the `heat_flux_range` to calculate the `offsets_vertices`. These are linear offsets to get neighboring cells/vertices. Since the volumes of the ranges are not the same (there are N+1 vertices for N cells in 1D), the linear offsets were incorrect, and the wrong cells were fetched. This resulted in NaNs in the corners due to the harmonic averaging. 1D simulations were not affected because the offsets_vertices remain `[-1 0]` and the offsets_centers `[0 1]`; the range volume doesn't manifest here at all.
Additionally renaming some indices in the `non_ideal` header to be consistent with the rest of the file and removing some trailing white spaces.

Offset generation for stagered grids

---

Makefile
configure

This is a variation of PR #228 
It moves some things around and defines some paths in a different way in the configure file, so that we can install in non-default locations. It works as follows:
1. If only --prefix is passed, it uses that as the location of the dependencies and the location where gkylzero is installed.
2. Regardless of whether --prefix is passed or not, the paths favor --*-inc and --*-lib when those are given.
I believe we thought non-default install location was working because it was looking for these libraries in $HOME/gkylsoft, and we all had an install there from previous work. But if that doesn't exist it in fact doesn't work. This PR fixes that.

Reorganize configure to support install in nondefault locations

---

install-deps/mkdeps.sh
unit/mctest_mpi_comm.c
zero/mpi_comm.c

Basically put stuff in mpi_comm associated in decomp inside an if statement so we can create an mpi_comm with decomp=0, i.e. without decomposition. In this case mpi_comm is used solely as a communicator (see comment in 521de203a76f5b0a794f676266ea38e9cec89f2d)

Make decomp an optional input to mpi_comm

---

apps/gk_field.c
apps/gkyl_gyrokinetic.h
apps/gyrokinetic.c
regression/rt_gk_ion_sound_adiabatic_elc_1x2v_p1.c
regression/rt_gk_lbo_relax_1x2v_p1.c
regression/rt_gk_lbo_relax_varnu_1x2v_p1.c
regression/rt_gk_ltx_boltz_elc_1x2v_p1.c
regression/rt_gk_mirror_boltz_elc_1x2v_p1_nonuniform.c
regression/rt_gk_mirror_boltz_elc_1x2v_p1_nonuniform_nosource.c
regression/rt_gk_mirror_boltz_elc_1x2v_p1_uniform.c
regression/rt_gk_sheath_1x2v_p1.c
zero/gkyl_eqn_type.h

- Rename the GK_FIELD_ADIABATIC option to GK_FIELD_BOLTZMANN, since in 2 papers we've referred to that as the Boltzmann electron model.
- Implement a new GK_FIELD_ADIABATIC, only in 1x for now, in which the electrons are not evolved and they simply contribute to the charge density in the Poisson equation with n_e = n_e0*(1 + e*phi/T_e).
- Tested GK_FIELD_ADIABATIC (one CPU and GPU) with one of the ion acoustic Landau damping tests in the GkLBO paper and it qualitatively looks very similar, and quantitatively is only 12% off (but I didn't try to do resolution convergence).
This also fixes a bug for 1x simulations with geometry in that the polarization weight was not multiplied by jacobgeo.

Implement adiabatic elc option (only for 1x). Rename previous GK_FIELD_ADIABATIC to GK_FIELD_BOLTZMANN

---

machines/configure.perlmutter.gpu.sh
machines/jobScript.perlmutter-gpu
machines/mkdeps.perlmutter.gpu.sh

The problem was we were not using cray mpich, and were not disabling cuda-aware MPI. Now sims appear to run reliably.

Update perlmutter machine files

---

unit/ctest_array.c
zero/alloc.c
zero/array.c

ctest_array passes on CPU and GPU

Zero out gkyl_array upon creation (for type int/float/double)

---

zero/proj_maxwellian_on_basis.c
zero/proj_maxwellian_on_basis_cu.cu

Add standard protections in non-gk project maxwellian functions. Add a new protection against overflow in the exponential when vtsq < 0 for all project maxwellian functions (gk and non-gk). ctest_proj_maxwellian_on_basis passes.

Gk g0 app maxproj protections

---

unit/ctest_bgk_sr.c
unit/ctest_correct_mj_integrated.c
zero/correct_mj.c
zero/gkyl_correct_mj.h
zero/gkyl_correct_mj_priv.h

Cleanup for Maxwell-Juttner correction routine.
- Adds a ctest for spatially variable corrections.
- Error in the moments is now checked as the maximum of the entire domain. The tolerance has been lowered to allows for certain slowly converging regions.
- [WIP] ctest_bgk_sr.c will need to be migrated into the regression tests. Currently broken as of commit: #296.
Note A: The ctest routine works well and corrects all moments and their expansions, but the error is only checked for the mean value of the moment in a cell. Future improvements could ensure the projection converges the mean and further expansions, but I really don't think this is necessary.)
Note B: Future work to potential improve this and compute cell by cell error and stop the iterator might be worth while, but it might just …

Maxwell-Juttner Fix cleanup

---

apps/gkyl_vlasov.h
apps/gkyl_vlasov_priv.h
apps/vlasov.c
apps/vm_species_bgk.c
regression/rt_neut_sr_bgk_sod_shock_1x1v_p2.c
zero/gkyl_vlasov_lte_correct.h
zero/vlasov_lte_correct.c

Added dynvec for correct-lte all-moments which gives, number iter, status of convergence, and 5 error components for [n, u, T/m]
Note: The conversion of the status to a dynvec is done by hand at the moment @ammarhakim if you have a different way to do this before merge please comment. https://github.com/ammarhakim/gkylzero/compare/main...lte_corr_dynvec#diff-5e12ac2b111acab49c53e4b55c5ebdcbbd481f2ce7357eec1e1336caf1bec0d1R131

Added dynvec for correct lte all moms status

---

apps/gkyl_moment_priv.h
apps/mom_field.c
apps/mom_priv.c
apps/mom_species.c
regression/rt_10m_burch_grad_closure.c
unit/ctest_range.c
unit/ctest_rect_decomp.c
unit/mctest_mpi_comm.c
zero/gkyl_comm.h
zero/gkyl_comm_priv.h
zero/gkyl_range.h
zero/mpi_comm.c
zero/null_comm.c
zero/range.c
zero/rect_decomp.c

I have now completed the corner syncs, including for periodic BCs. This is hooked into both the null and mpi comm. But not for nccl. For now this is ok as no GK or VM updater needs corner BCs. But moments do, however, they do not work on GPUs anyway.  Eventually, we will need to implement this in nccl also.

Corner syncs added to communicator system

---

apps/gk_species.c
apps/pkpm_field.c
apps/vm_field.c
regression/rt_gk_lapd_cyl_3x2v_p1.c
regression/rt_gk_sheath_3x2v_p1.c
regression/rt_hyper_vlasov_tm.c
unit/ctest_dg_rad_gyrokinetic.c
unit/ctest_hyper3x_dg.c
unit/ctest_hyper_dg.c
zero/dg_updater_diffusion_fluid.c
zero/dg_updater_diffusion_gen.c
zero/dg_updater_diffusion_gyrokinetic.c
zero/dg_updater_diffusion_vlasov.c
zero/dg_updater_fluid.c
zero/dg_updater_fpo_vlasov.c
zero/dg_updater_gyrokinetic.c
zero/dg_updater_lbo_gyrokinetic.c
zero/dg_updater_lbo_pkpm.c
zero/dg_updater_lbo_vlasov.c
zero/dg_updater_pkpm.c
zero/dg_updater_rad_gyrokinetic.c
zero/dg_updater_vlasov.c
zero/gkyl_dg_updater_gyrokinetic.h
zero/gkyl_hyper_dg.h
zero/gkyl_hyper_dg_priv.h
zero/hyper_dg.c
zero/hyper_dg_cu.cu

Previously when we specified zero flux BCs, they had to be used for both boundaries along a direction. This change allows us to specify it on only one side. Made the change in hyper_dg, but only the GK app can use it now.
Also make a couple of style changes in hyper_dg:
- replace hdg with up (like many other updaters).
- Make the _cu methods private and call them if use_gpu is true.

Ability to specify zero flux BCs on one boundary only and design changes in hyper_dg

---

regression/rt_5m_mom_beach.c
zero/moment_em_coupling.c

The first is that we had too many factors of epsilon0 in the implicit source solve (one of the unknowns is epsilon0*E, so the applied current does not need to be divided by epsilon0). The other was that the moment regression refactor changed x_last_edge to be on the high density side instead of the low density side. We want the waves to propagate from the low density side. Changing back.

In the process of debugging the DG two-fluid solver, I discovered two issues:

---

zero/gkyl_dg_eqn.h

These methods should help to have a clear idea of what the function pointers inside dg_eqn are. Eventually we will follow gkyl_wv_eqn and actually call these methods within hyper_dg but for now this is just to add some additional information to the header file that can help new developers navigate the complexity of the dg_eqn object.

Adding a couple methods with detailed doxygen-style comments for future developers

---

unit/ctest_alloc.c
zero/alloc.c

1. For GPUs: change gkyl_mem_buff_resize so it preserves the data originally in the buffer, which is the current behavior on CPU.
2. Add a unit test for gkyl_mem_buff.
We are using this object in setting up TS BCs and noticed these missing pieces.

Preserve data in mem_buff upon resizing on the GPU, and test mem_buff

---

unit/ctest_alloc.c
zero/alloc.c
zero/vlasov_lte_proj_on_basis_cu.cu

Bug fix in Vlasov LTE where the CUDA file would seg fault when running if you weren't doing a canonical Poisson bracket case.

Gk g0 app main merge

---

apps/gk_neut_species_react.c
regression/rt_gk_sheath_1x2v_p1_cons.c
regression/rt_gk_sheath_3x2v_p1_cons.c
regression/rt_gk_step_1x2v_p1_cons.c
regression/rt_gk_step_3x2v_p1_cons.c
zero/dg_iz.c
zero/dg_iz_cu.cu

Conservation fixes. The conservation tests verify the correct amount of energy is lost/gained for ionization,  recombination, and charge exchange for ions, electrons, and neutrals (dynamic). Tests are done in Cartesian and step geometry to verify correctness. There are 1x2v tests with static neutrals and 3x2v tests with dynamic neutrals. 
(gk-g0-app-neut is still a prototyping branch)

Gk g0 app neut conservation fixes

---

unit/ctest_mat.c
zero/gkyl_mat.h
zero/gkyl_mat_priv.h
zero/gkyl_vlasov_lte_proj_on_basis.h
zero/gkyl_vlasov_lte_proj_on_basis_priv.h
zero/mat.c
zero/vlasov_lte_proj_on_basis.c
zero/vlasov_lte_proj_on_basis_cu.cu

This is the production version of the cublasDgemm prototyping branch, see [DR](https://github.com/ammarhakim/gkylzero/issues/400). Primarily for computing with cblas/cublas the matrix multiplication: alpha*A(gkyl_mat) * B(gkyl_array/gkyl_mat) + Beta*C(gkyl_array/gkyl_mat) = C(gkyl_array/gkyl_mat). This has been used successfully to reduce the computation time of the nodal to modal conversion in vlasov-lte-proj-on-basis-cu, which we found to be more efficient than loop unrolling on GPU for this specific bottlenecked operation. 
Extensions to gkyl_mat functions:
- _gkyl_mat_mm_array_mem_, new structure to save the matrix A and associated, alpha, beta, transposition information for the matrix multiply.
- **gkyl_mat_mm_array_mem_dev_new**, Builds a new object for computing CPU/GPU side matrix …

dg_10m cublasDgemm production

---

apps/gkyl_vlasov.h
apps/gkyl_vlasov_priv.h
apps/vlasov.c
apps/vlasov_forward_euler.c
apps/vlasov_update_implicit_coll.c
apps/vm_species.c
apps/vm_species_bgk.c
apps/vm_species_lte.c
regression/rt_can_pb_neut_bgk_sodshock_1x1v_p2.c

DR: [https://github.com/ammarhakim/gkylzero/issues/414](url) 
Description: 
This branch primarily does the following: 
-	Creates a new structure vm_lte, used within gkyl_vm_species to store moments/projection object/f_lte
-	Used in two places currently: (NEW) io of f_lte, and in the BGK collision routine to create f_lte.
-	New io flag (in the vm_species): output_f_lte 
Additions:
New file: vm_species_lte. This contains the functions: (no gkyl_... since they are private to vm)
```
// Initialize species lte object.
void vm_species_lte_init(…);
// Compute necessary moments for f-lte creation
void vm_species_lte_moms(…);
// Compute f-lte
void vm_species_lte(…);
```
With the new struct:
```
struct vm_lte {  
struct gkyl_array *f_lte;
struct vm_species_moment moms; // moments needed in the …
```

f-lte io and BGK Collision Restructuring

---

zero/dg_rad_gyrokinetic_drag_cu.cu

The setting of the normalization factor for the minimum radiation temperature was not done on GPUs, so no radiation occurred with GPUs. It is now set the same as on CPUs.
Radiation regression test previously had 0 energy loss on GPUs. Energy loss on GPUs now matches energy loss on CPUs.

Merge normalization on GPUs

---

zero/bc_emission_elastic.c
zero/gkyl_bc_emission_elastic.h

An inclusion call to the private header `gkyl_bc_emission_elastic_priv` in the public header of the same object was causing build issues. This inclusion call has been moved to `bc_emission_elastic`.

gk-g0-app emission header fix

---

apps/gkyl_vlasov_priv.h
apps/vlasov.c
apps/vm_species_emission.c
zero/bc_emission.c
zero/bc_emission_spectrum.c
zero/gkyl_bc_emission.h
zero/gkyl_bc_emission_spectrum.h
zero/rect_grid.c

A number of minor modifications to the emission BC are necessary for it to work properly when the impacting species and emitted species are different and have different boundary grids.
- The emission spectrum was being projected onto the impacting grid instead of the emitting grid, this has been fixed with both grids being passed to the updater.
- The update range was using the emitted boundary range for the weighting of the yield instead of the impacting boundary range.
- A diagnostic was added to output the emitted distribution in the ghost cell in a separate file `bc_up` or `bc_lo`.
- The relaxation of the BC using `t_bound` wasn't quite working, a check was added to correctly cut off the scaling at the appropriate time.
- A preset for the ion-impact secondary electron emission of …

gk-g0-app cross-species emission fixes

---

apps/gk_species.c
apps/gkyl_gyrokinetic_priv.h
apps/gyrokinetic.c
kernels/gyrokinetic/gkyl_mom_gyrokinetic_kernels.h
kernels/gyrokinetic/gyrokinetic_int_mom_1x1v_ser_p1.c
kernels/gyrokinetic/gyrokinetic_int_mom_1x1v_ser_p2.c
kernels/gyrokinetic/gyrokinetic_int_mom_1x2v_ser_p1.c
kernels/gyrokinetic/gyrokinetic_int_mom_1x2v_ser_p2.c
kernels/gyrokinetic/gyrokinetic_int_mom_2x2v_ser_p1.c
kernels/gyrokinetic/gyrokinetic_int_mom_2x2v_ser_p2.c
kernels/gyrokinetic/gyrokinetic_int_mom_3x2v_ser_p1.c
kernels/gyrokinetic/gyrokinetic_mom_1x1v_ser_p1.c
kernels/gyrokinetic/gyrokinetic_mom_1x1v_ser_p2.c
kernels/gyrokinetic/gyrokinetic_mom_1x2v_ser_p1.c
kernels/gyrokinetic/gyrokinetic_mom_1x2v_ser_p2.c
kernels/gyrokinetic/gyrokinetic_mom_2x2v_ser_p1.c
kernels/gyrokinetic/gyrokinetic_mom_2x2v_ser_p2.c
kernels/gyrokinetic/gyrokinetic_mom_3x2v_ser_p1.c
regression/rt_gk_sheath_3x2v_p1.c
zero/gkyl_gyrokinetic_maxwellian_moments_priv.h
zero/gkyl_mom_gyrokinetic_priv.h
zero/gyrokinetic_maxwellian_moments.c
zero/mom_gyrokinetic.c
zero/mom_gyrokinetic_cu.cu
zero/proj_bimaxwellian_on_basis.c

New feature:
- A FourMoments option for GK which calculates M0, M1, M2par and M2perp together.
Two fixes:
1. Previously we were making the positivity shift diagnostic moments the same as those the user requested. But when the user requests Maxwellian or BiMaxwellian moments one gets a division error at t=0 when computing upar of the positivity shift, because its density is zero. We fix this by simply making the diagnostic for pos shift always be FourMoments.
2. Fix a missing factor of 0.5 in the proj_bimaxwellian_on_basis_lab_mom. It had snuck in when we changed the definition of M2perp.
This goes with PR 44 in gkylcas: https://github.com/ammarhakim/gkylcas/pull/44

Fix a bug in the positivity shift diagnostics and in proj_bimaxwellian_on_basis, and implement FourMoments

---

zero/gyrokinetic_maxwellian_moments.c

Fix an issue with maxwellian moments with vdim. It didn't know what the basis was initially. Seems like commit [https://github.com/ammarhakim/gkylzero/commit/0c09950b2bcc9be5f7acb7bdadb7b7cd292998ed](url) wasn't tested before it was pushed.
Sometimes 1 line of code takes hours to debug

Bug fix in maxwellian_moments updator

---

regression/rt_gk_asdex_3x2v_p1.c
regression/rt_gk_solovev_out_3x2v_p1.c
regression/rt_gk_step_1x2v_p1_cons.c
regression/rt_gk_step_3x2v_p1_cons.c
regression/rt_gk_step_out_2x2v_p1.c
regression/rt_multib_step_2x2v_p1.c
regression/rt_multib_step_sol_2x2v_p1.c
unit/ctest_asdex.c
unit/ctest_cerfon.c
unit/ctest_efit.c
unit/ctest_elliptical_surfaces.c
unit/ctest_gk_geometry_mirror.c
unit/ctest_step_compare.c
unit/ctest_step_outboard.c
unit/ctest_time_roots.c
zero/efit.c
zero/efit_utils.c
zero/gkyl_efit.h
zero/gkyl_efit_priv.h
zero/gkyl_mirror_geo_priv.h
zero/gkyl_tok_geo_priv.h
zero/mirror_geo.c
zero/tok_geo.c

Fixes issue #480: Serendipity basis is no longer used at all for Psi(R,Z) when using efit for geometry. Along with this we also fix a memory leak in efit.c. Also clean up some unit and regression tests, removing the rz_basis_type option for all of them.
(MF) Also fit some bugs:
1. The case in which psi increases with x was not handled properly in efit.c, leading to a nonsensical flux grid.
2. Redefined variables and variables with mixed scope were giving seg faults on Macs (but not Linux) even though the test was valgrind clean.

Gk g0 app xptfinder bugfix

---

zero/dg_basis_ops.c
zero/efit.c
zero/gkyl_dg_basis_ops.h
zero/mirror_geo.c
zero/tok_geo.c

This is a bug fix that affects mirror geometry on the magnetic axis. Before commit 4ce1631, there was a memory error that obscured this issue. When @manauref was trying to run mirror calculations post this commit, he noticed the error. We have tracked it back to this mistake which fixes the issue.
Error in the eval_cubic_wgrad2 function in dg_basis_ops: Accidentally returned only one of the second derivatives and the mixed partial rather than both second derivatives and the mixed partial. (This is for the 2x case). This was breaking on axis calculation of bmag for the mirror.
This wgrad2 function is supposed to return f, d^2f/dx^2, d^2f/dy^2, and d^2f/dxdy which it now does.

Fix an error in the eval_cubic_wgrad2 function

---

zero/gkyl_deflated_fem_poisson.h
zero/gkyl_deflated_fem_poisson_priv.h

Address issue #488 by adding comments to the deflated_fem_poisson header files. This is a small enhancement that does not change any code, only comments and the name of one variable in the header declaration of gkyl_deflated_fem_poisson_new.

Comments in gkyl_deflated_fem_poisson Headers

---

apps/gk_species.c
apps/gkyl_gyrokinetic_priv.h
apps/gyrokinetic.c
zero/gkyl_positivity_shift_gyrokinetic.h
zero/positivity_shift_gyrokinetic.c
zero/positivity_shift_gyrokinetic_cu.cu

There is a single line of code changed here. I think that the positivity fix should be fine by just skipping the electron loading in line 2431. The else statement in the loop should just evaluate everything to 1 because it's not loading the moments of the electrons. Addressing issue #494

Single species positivity fix

---

apps/gkyl_gyrokinetic_multib.h
apps/gkyl_gyrokinetic_multib_priv.h
apps/gkyl_gyrokinetic_priv.h
apps/gyrokinetic.c
apps/gyrokinetic_multib.c
apps/gyrokinetic_multib_update_ssp_rk3.c
apps/gyrokinetic_update_ssp_rk3.c
regression/rt_gk_step_out_2x2v_p1.c
regression/rt_multib_step_2x2v_p1.c
regression/rt_multib_step_b2_2x2v_p1.c
zero/efit_utils.c

Add the GK multiblock (MB) update method, and I/O methods that mimic the single block methods. These changes are the minimum necessary for the MB to run with a single block, producing identical results to the single block app, while also setting a path for running with multiple blocks with minimal changes.
**Update method:**
This required splitting the forward Euler in the single block app so that we can compute df/dt (in the _rhs method) without performing an actual time step. The single block _rhs method still reduces the CFL frequency in its block, and returns a minimum dt, `dt_min` (we may want to change/move this, more on this below). 
The MB update calls the MB ssp_rk3, and in each stage it does 4 things:
1. It loops over the blocks, calling gyrokinetic_rhs for each. Again, this …

MB app update and other methods

---

Makefile
unit/ctest_struct_of_arrays.c
unit/ctest_struct_of_arrays_cu.cu
unit/gkyl_struct_of_arrays.h

Just a unit test showing how to use structs to wrap arrays to create arrays of gkyl_arrays, or arrays of arrays of gkyl_arrays.
It's kind of amazing that one can do this, especially since I think (not tested, just though of this now) you could simply use a single struct with recursion and create arrays of arrays of arrays of..
We are trying to use similar workflows in radiation, so I wanted to demo/test it here.
FYI @jRoeltgen

A unit test with a struct-based approach to arrays of arrays v2

---

zero/efit_utils.c

Increase tolerance in x-point finder to 1e-18: Low tolerance ( grad(psi) < 1e-19 ) was causing the x-point not to be found on stellar-amd for the rt_gk_step_out_2x2v_p1 regrssion test. Perlmutter, local linux machine, stellar-intel, and local mac machine were fine. This change does not affect the result on local linux machine.

Stellar-amd Rfit Tolerance Bug Fix

---

apps/vlasov.c

Somehow it slipped under our noses that there were issues with VP restarts. They were working in an earlier iteration, but at some point they broke because they were calling a VM method that doesn't exist for VP.
Fix restarts by:
- Putting an if-statement in the app_read_from_frame method checking that we are not doing VP before calling `vm_field_apply_bc`.
- If doing VP, compute the initial field, external fields, and apply BCs.
Tested with:
- rt_vlasov_weibel
- rt_vlasov_poisson_sheath_Bext
both sims ran with a single run, or with 1 restart, getting visually identical field-energy time traces in each case.

Fix VP restart

---

apps/gk_neut_species_react.c
apps/gk_species_react.c
apps/gkyl_gyrokinetic_priv.h

There are some instances where "partner" moments refer to ion moments, and it is confusing. I propose that "partner" only refers to neutrals in CX. Ion moments should be referred to explicitly as "ion" moments for code readability.
Also, adding missing calculation for ion moments to project neut LTE in recombination term of gk neut species.

Changing some names of the moments in neutral react apps for clarity.

---

apps/gk_species_lbo.c
apps/gkyl_gyrokinetic_priv.h

In the GK LBO we had not divided M0 by jacobgeo before computing nu_sr with it (and the Greene prefactor in cross collisions). This means that in mapped geometries with normNu or cross species collisions our collision frequency was incorrectly scaled by factor of J.
NOTE: I think similar bugs remain in gk_species_bgk, but I didn't fix them here since that module is being modified heavily in the gk-g0-app-hack24 branch.

Bug fix: divide M0 by jacobgeo in GK LBO app

---

unit/ctest_gk_geometry.c
zero/calc_metric.c
zero/gk_geometry.c
zero/gk_geometry_cu.cu
zero/gk_geometry_mapc2p.c
zero/gk_geometry_mirror.c
zero/gk_geometry_tok.c
zero/gkyl_calc_metric.h
zero/gkyl_gk_geometry.h

Add the magnitude of the duals to gk_geometry. @manauref plans to use these to address issue #538.
The unit test has been tested with valgrind on perlmutter and shows no memeory leaks. rt_gk_sheath_1x2v_p1 also shows no memory leaks.

Add Magnitude of Dual Vectors to gk_geometry

---

apps/vlasov.c

For the emission BCs to restart correctly, the boundary fluxes must be calculated prior to the boundary conditions being applied. This was in place on one of the production branches, but seems to have been lost at some point during one of the branch merges.

Add bflux calculation to restarts

---

zero/gk_geometry.c

Fix issue where reduce_bmag function returned before releasing temporary arrays.

Fix Valgrind Errors in Reduce Bmag

---

regression/rt_gk_wham_nonuniformx_1x2v_p1_numeric.c
unit/ctest_position_map.c
zero/gk_geometry_mapc2p.c
zero/gk_geometry_mirror.c
zero/gk_geometry_tok.c
zero/gkyl_position_map_priv.h
zero/mirror_geo.c
zero/tok_geo.c

Consider the case where the position map is not provided as an input to the geometry generation. This often happens in a unit test for the geometry modules. The geometry needs to call the position map functions, even if they are identity maps. For this, a temporary position map must be created and destroyed.

Fix a small oversight in the position map usage in the unit tests

---

unit/ctest_array_average.c

One small change on the ctest for array_average where we used a >2months old call of the array_integrate_advance routine.

Quick fix of a compatibility issue in ctest_array_average with array_integrate updater

---

apps/gk_neut_species.c
apps/gk_neut_species_react.c
apps/gk_neut_species_source.c
apps/gk_species.c
apps/gk_species_bgk.c
apps/gk_species_lbo.c
apps/gk_species_radiation.c
apps/gk_species_react.c
apps/gk_species_source.c
apps/gkyl_gyrokinetic.h
apps/gkyl_gyrokinetic_priv.h
apps/gyrokinetic.c
regression/rt_gk_static_3x2v_p1.c

Write functions now live in their respective objects, i.e. species, lbo, radiation, react.  This corresponds to DR https://github.com/ammarhakim/gkylzero/issues/581. 
The write functions for the `react` objects were also simplified, removing all the if statements for the different reactions in `gyrokinetic.c`.

Restructure write functions

---

machines/configure.della-cpu.sh
machines/configure.della-gpu.sh
machines/configure.linux.cpu.sh
machines/configure.linux.gpu.sh
machines/configure.macos.sh
machines/configure.perlmutter.cpu.sh
machines/configure.perlmutter.gpu.sh
machines/configure.satori.cpu.sh
machines/configure.satori.gpu.sh
machines/configure.stellar-amd.sh
machines/configure.stellar-intel.sh
machines/configure.traverse.dev.sh
machines/configure.traverse.host.sh

Following internal discussions, I've updated the configuration files for all presently supported architectures to run the configuration script with the `--use-lua` flag set to `yes` by default. I also removed the default `--use-mpi=yes` and `--use-adas=yes` flags from the Mac OS and Linux configuration files, since both MPI and ADAS should (in contrast to Lua) be considered optional dependencies for Gkeyll, and so should not be included in the configuration unless we are building on a known machine which definitely has them installed.

Updating g0 machine files to build with Lua by default

---

regression/rt_gk_static_3x2v_p1.c
zero/dg_cx.c
zero/dg_cx_cu.cu
zero/gkyl_dg_cx.h
zero/gkyl_dg_cx_priv.h

The CX updater functions and methods of kernel selection are now optimized for CUDA to avoid memory leaks. Structure is now consistent with other cuda updaters in zero directory. Tests with CX are valgrind clean and results are consistent with main branch.

Fix CX updater for CUDA

---

regression/rt_gk_step_out_2x2v_p1.c

Fix an oversight in the step regression test. The block type should not be set to DN_OUT_MID now that we use the global tokamak normalization. Instead it should just be DN_OUT.
Single Block should no longer use separated block types such as OUT, MID, and LO unless someone is trying to do something special. This test was odd from the beginning any way. All other step reg tests use DN_OUT, which this one now matches.

Fix mistake in STEP regression test where block type was incorrect. 

---

apps/gk_species.c
apps/gk_species_bflux.c

The bflux integrated moment function for static species wasn't initialized leading to a seg fault when the following was called in gyrokinetic.c: 
```
void
gkyl_gyrokinetic_app_calc_species_boundary_flux_integrated_mom(gkyl_gyrokinetic_app* app, int sidx, double tm)
{
struct gk_species *gks = &app->species[sidx];
gk_species_bflux_calc_integrated_mom(app, gks, &gks->bflux_diag, tm);
}
```
Now fixed and rt_gk_static test runs.

Fixing bflux seg fault in static species after new boundary flux features were added

---

regression/rt_gk_wham_1x2v_p1.c
zero/gkyl_mirror_geo_priv.h

Geometry was not being generated correctly with the cubics for the mirror. I fixed it in 2 lines.
Description: The field lines need to be traced with the cubic integrator. This was not passed correctly. It was found by comparing it against the tokamak code.
Issue link: No issue. Serendipitous discovery
Call gkyl_mirror_geo_R_psiZ instead of R_psiZ
Impacted files: gkyl_mirror_geo_priv.h
Let's examine this rt_gk_wham_1x2v unit test with the cubics flag. 32 cells in z to make it speedy.
Before fix: SIGABRT
Geometry after fix:

Mirror geometry cubics fix

---

apps/gk_field.c
apps/gkyl_gyrokinetic_priv.h
unit/ctest_ambi_bolt_potential.c
zero/ambi_bolt_potential.c
zero/gkyl_ambi_bolt_potential_priv.h

Description: In calculating the sheath values for the Boltzmann electron model, there is an apparent average that the app does. The code reads like this. This is exclusive to 1x.
First, sheath_vals[0] calculates the density and sheath potential on the left edge. Then, sheath_vals[1] calculates density and sheath potential on the right edge. The rest of the arrays are zero. We want one array with all these quantities, so they are accumulated (out = out + 1 * inp).
```
gkyl_array_accumulate(field->sheath_vals[0], 1., field->sheath_vals[1]);
gkyl_array_scale(field->sheath_vals[0], 0.5);
```
If all the sheath values were 1, the arrays would look like this:
sheath_vals[0] = {1,0,0, ... , 0,0,0}
sheath_vals[1] = {0,0,0, ... , 0,0,1}
We want a result:
sheath_vals[0] = {1,0,0, ..., 0,0,1}
This …

Bug fix: Boltzmann electron sheath values were half

---

zero/dg_calc_canonical_pb_fluid_vars.c
zero/dg_calc_canonical_pb_fluid_vars_cu.cu

so that the logic that I copied from other DG equations works correctly for not indexing an unallocated array. I was accidentally being saved by certain compilers being okay with this while others were not.

The adiabatic coupling array needs to be initialized to 0 

---

apps/gkyl_vlasov.h
apps/gkyl_vlasov_priv.h
apps/vlasov_lw.c
apps/vm_field.c
regression/lua/rt_vlasov_buneman_1x1v_p2.lua
regression/lua/rt_vp_buneman_1x1v_p2.lua

As part of my continued desire for every bit of Ammar's simulation journal to be a regression test within the code so that no confusion arises between old versions and new versions of Gkeyll, I am reintroducing the ghost currents capabilities with the same optional useGhostCurrents functionality in the input files. Also include both a Vlasov-Poisson and Vlasov-Maxwell + ghost currents Buneman instability test.

Optional ghost currents functionality in 1x Vlasov-Maxwell

---

kernels/bgk/gyrokinetic_cross_prim_moms_bgk_1x1v_ser_p1.c
kernels/bgk/gyrokinetic_cross_prim_moms_bgk_1x1v_ser_p2.c
kernels/bgk/gyrokinetic_cross_prim_moms_bgk_1x2v_ser_p1.c
kernels/bgk/gyrokinetic_cross_prim_moms_bgk_1x2v_ser_p2.c
kernels/bgk/gyrokinetic_cross_prim_moms_bgk_2x2v_ser_p1.c
kernels/bgk/gyrokinetic_cross_prim_moms_bgk_3x2v_ser_p1.c

Modify the condition of turning off cross collision. It used to turn off cross collision when the product of vtsq_sr at each corner is negative, which is wrong because the product can be positive when vtsq_sr is negative at even number of corners. Now it turns off cross collision when vtsq_sr is negative at any quadrature point.

Modify the kernels to calculate BGK cross primitive moments. 

---

apps/gk_field.c

Small fix in logical that I found thanks to a CPU compilation warning.
BTW: I recommend to compile using `make -j 12 install > mk.out` so that the normal output is redirected to the `mk.out` file. In that way, the terminal displays only the warnings and error and it's much easier to catch them that way.
E.g. when I compiled the main I just had:
```
ahoffman@ahoffman-lt ~/g/gkylzero (main)> make -j 12 install > mk.out
apps/gk_field.c:361:9: warning: logical not is only applied to the left hand side of this comparison [-Wlogical-not-parentheses]
361 |     if (!f->gkfield_id == GKYL_GK_FIELD_BOLTZMANN)
|         ^              ~~
apps/gk_field.c:361:9: note: add parentheses after the '!' to evaluate the comparison first
361 |     if (!f->gkfield_id == GKYL_GK_FIELD_BOLTZMANN)
|         ^ …
```

fix of logical in gk_field.c

---

apps/gk_neut_species.c
apps/gk_neut_species_moment.c
apps/gk_neut_species_projection.c
apps/gkyl_gyrokinetic_priv.h
apps/gyrokinetic.c
kernels/neutral/gk_neut_hamil_1x3v_tensor_p1.c
kernels/neutral/gk_neut_hamil_2x3v_tensor_p1.c
kernels/neutral/gk_neut_hamil_3x3v_tensor_p1.c
regression/rt_gk_neut_recycle_1x3v_p1.c
regression/rt_gk_step_2x2v_p1_cons.c
zero/calc_metric.c

This goes with [PR 73 in gkylcas](https://github.com/ammarhakim/gkylcas/pull/73).
Don't merge either before testing your ICs first @akashukla @tnbernard .
The initial temperature is coming out incorrect for Canonical PB neutrals. I suspect that it is incorrect in calculations in the time loop too. My hypothesis is that this is happening because the Hamiltonian is computed with a reorganized metric tensor (for cdim<3), but the projection of ICs and/or calculation of moments is using the non-reorganized metric.
Here we fix this by using Hamiltonian-computing kernels that don't reorganize the metric, and instead we give the species its own metric array, which it reorganizes if needed, and the hamiltonian, the projection of ICs, and moment calculators all use this reorganized metric.
NOTE:
I …

Create a species metric in Canonical PB neutrals to fix projections/moments

---

zero/gkyl_wv_maxwell_priv.h

As pointed out by @manauref, the changes I made in PR #657 broke the GPU build, essentially because of the use of the host-side `gkyl_malloc` and `gkyl_free` functions within the `wv_maxwell` equation object, which needs to be instantiatable on _both_ host and device because of the way the Vlasov app works. Sorry! I've now restructured the equation object to allocate all arrays on the stack and to avoid the use of these functions entirely. The GPU build now works on Stellar-AMD, although it would be good to verify this independently. Apologies for the inconvenience!

Fix broken wv_maxwell equation object on GPUs

---

apps/gk_species_lbo.c
regression/rt_gk_wham_1x2v_p1.c

Purpose: This code already existed. I want to re-enable it so I can look at the collision frequency in the mirror simulations. I checked and this runs on the regression test on CPU.

Re-enable diagnostics for the spatially dependent collision frequency

---

apps/gk_neut_species_lte.c

The 1d tests in cylindrical geometry produces expected results now.

Fixing LTE moms for gk neut to use correctly ordered g_ij and gij.

---

zero/gk_maxwellian_correct.c
zero/gk_maxwellian_correct_cu.cu

Normalize the error in u_par by thermal velocity when u_par is smaller than thermal velocity.
Fix a bug in computing the relative u_par error when u_par is larger than thermal velocity: the denominator should be the absolute value of u_par instead of u_par itself since it can be negative.

Update the normalization of u_par error.

---

zero/gkyl_position_map.h
zero/gkyl_position_map_priv.h
zero/position_map.c

The issue is that the position map was allocating `double foo[]` objects of hundreds of lengths, which was overflowing the stack. Instead, we should malloc this kind of memory and free it.
The memory can be allocated when bmag is set and the `to_optimize` flag is tripped. Without having B in the position map, these objects are not used because there is no magnetic field to loop over. It's also a convenient flag to use in memory-free operations.
Before this fix, Perlmutter segfaulted at a later stage of the optimization because memory was freed from the stack that it needed to access.
rt_gk_wham_nonuniformx_1x2v_numeric is valgrind clean.
Valgrind did not show me any issues with a stack overflow here.
Tested on stellar-amd, personal Ubuntu 24.04, and perlmutter with …

Stack overflow memory issues in position map

---

apps/gk_field.c
apps/gk_species.c
apps/gkyl_gyrokinetic.h
apps/gkyl_gyrokinetic_multib.h
apps/gkyl_gyrokinetic_priv.h
apps/gyrokinetic.c
apps/gyrokinetic_multib.c
regression/rt_gk_d3d_iwl_2x2v_p1.c
regression/rt_gk_d3d_iwl_3x2v_p1.c
regression/rt_gk_ltx_iwl_2x2v_p1.c
zero/gk_geometry.c
zero/gk_geometry_cu.cu
zero/gk_geometry_mapc2p.c
zero/gk_geometry_tok.c
zero/gkyl_gk_geometry.h

Some of the ranges in GK IWL clopen simulations were wrong (off by 1). For sure the global core range is wrong, and it's likely the extended core and sol ranges were also wrong.
Here we correct that.
Also, to avoid numerous definitions of LCFS related quantities (i.e. the index of the cell to its left, and the core and sol ranges) throughout the app (i.e. in GK app, in species, field, sources, bflux), and thus having an increased risk for making a mistake, we centralize the location of the LCFS parameters (x_LCFS and idx_LCFS_lo) to gk_geometry, and the ranges are only created in one place (in gyrokinetic for conf- and in species for phase-space). This way other modules can simply fetch them from these places rather than creating them again. This addreses issue #711 .
Here's proof that …

Correct and centralize creation of core/SOL ranges in IWL GK sims

---

zero/gk_geometry_cu.cu

The assert header in `gk_geometry_cu.cu` is missing and prevents compilation of main with GPU since PR #718 got merged.

microfix: missing assert header in gk geom cuda file

---

zero/deflate_zsurf.c
zero/gkyl_deflate_zsurf_priv.h

This PR addresses memory issues revealed by the [Compute Sanitizer](https://docs.nersc.gov/tools/debug/compute-sanitizer/).
By running:
```
compute-sanitizer --tool memcheck --leak-check full ./g0 -g -s1
```
on Perlmutter, we see that **the deflate zsurf updater is not properly deallocated on GPU.**
<details>
<summary>Click to show Compute Sanitizer error output</summary>
```
========= COMPUTE-SANITIZER
up_cu:0x7f13b9e54000  basis:0x1644658
in kernel: up:0x7f13b9e54000  basis:0x7f1ad3fffb48
up_cu:0x7f1a91d32e00  basis:0x1644658
in kernel: up:0x7f1a91d32e00  basis:0x7f1ad3fffb48
up_cu:0x7f178528fc00  basis:0x7f13b78026e8
in kernel: up:0x7f178528fc00  basis:0x7f1ad3fffb48
up_cu:0x7f17895fc400  basis:0x1644658
in kernel: up:0x7f17895fc400  basis:0x7f1ad3fffb48
up_cu:0x7f178d9e1e00 …
```

Add use_gpu attribute to gkyl_deflate_zsurf structure and fix gpu updater memory release

---

apps/gk_species.c

Small fix. This should not acquire the array that it's initializing. It should acquire the one that is already on the host.
Discovered when using the GKYL_IC_IMPORT_AF flag in the WHAM production simulations.
Tested using the above production test, and it exhibits the appropriate behavior.

Fix incorrect array acquisition in gk_species_file_import_init

---

unit/ctest_mirror_geo_dg.c
unit/ctest_mirror_grid_gen.c

I noticed that these tests were broken in CI, so I have to loosen the tolerances. This passes on Stellar-AMD and perlmutter. The version on Main does work without errors on my laptop, but CI and Stellar-amd have issues

Small fixes to mirror geometry unit tests

---

apps/gk_neut_species.c
apps/gk_species.c
apps/gkyl_gyrokinetic.h
regression/rt_gk_wham_1xIC_2x2v_p1.c

Description: When importing a single 1x field-line simulation into a multi-field line 2x simulation, there is no guarantee that the Jacobian will be the same. In general, when importing a lower-dimensional simulation to a higher-dimensional one, there is no guarantee of this. Since gkeyll writes out $Jf$, we must divide this by $J$ from the donor simulation, then multiply by $J$ of the current simulation to acquire f from the donor simulation.
The bug was fixed by also taking input of Jacobian inverse to the species reading table. The donor distribution function is multiplied by jacobgeo_inv, then up-projected to the higher dimension, then multiplied by jacobgeo.
Impacted files: gk_species.c, gk_neut_species.c
Automated testing: I added a regression test to import a single field line onto …

Bug fix: Importing 1x simulations into 2x simulations need the inverse jacobian

---

apps/gk_neut_species.c
apps/gk_species.c
apps/gkyl_gyrokinetic.h
regression/rt_gk_wham_1xIC_2x2v_p1.c

This PR wants to relax the assumptions when performing a restart from file using the structure
```
.init_from_file = {
.type = GKYL_IC_IMPORT_F,
.file_name = "restart-ion.gkyl",
.jacobgeo_inv_file_name = "restart-jacobgeo_inv.gkyl",
},
```
The current state of g0 prevents any restart if the bounds of the grid are changed. It could however be useful to start a simulation in a new geometry with a turbulent state that was previously obtained. E.g. when changing from negative triangularity (NT) to positive triangularity (PT), the simulation domain length in the binormal coordinate is changed because it is normalized to the safety factor which changes between both configurations.
This PR simply remove the assert that impeach the restart with different grid bounds. A restart can now be done …

Restart with a different geometry

---

apps/gk_field.c

Previous we had noticed that there was a valgrind error in closing the `field_energy_dot` file. It attribute it to the `fclose` in `with_file`:
```
mana@perlmutter:login32:~/perlmutter/gkeyll/code/g0-cpu/gkylzero> valgrind --leak-check=full --max-stackframe=2458976 ./build/regression/rt_gk_sheath_1x2v_p1 -s1
==1429448== Memcheck, a memory error detector
==1429448== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==1429448== Using Valgrind-3.20.0 and LibVEX; rerun with -h for copyright info
==1429448== Command: ./build/regression/rt_gk_sheath_1x2v_p1 -s1
==1429448==
==1429448== Syscall param write(buf) points to uninitialised byte(s)
==1429448==    at 0xB2DC213: write (in /lib64/libc-2.31.so)
==1429448==    by 0xB267EFC: _IO_file_write@@GLIBC_2.2.5 (in /lib64/libc-2.31.so) …
```

Fix uninitialized value in GK field app

---

unit/ctest_gyrokinetic_pol_density.c

The unit test for polarization density wasn't working correctly, so we had to make sure it was indexing the correct values. The numbers are only specified to 6 decimal places, so the best we can do is a tolerance of 1e-5. It's passing on my local computer (Ubuntu 24.04 flex), and Mana also checked on his Mac.

BUG FIX: polarization density unit test

---

gyrokinetic/Makefile-gyrokinetic
gyrokinetic/data/adas/process_adas.py
install-deps/download-adas.sh
install-deps/mkdeps.sh
machines/configure.stellar-intel.sh

see commit message.
Also: @tnbernard 's previous PR had also made it so that if the needed python modules are not detected, it downloads them. I've deleted that also because it would pollute the user's environment without them knowing it. For now we are basically reverting to the previous state of affairs, where the user must have installed the python modules themselves (and they are mentioned in the description of the --build-adas flag in mkdeps)

Move ADAS download back to mkdeps, but now the option is --build-adas.

---

moments/apps/moment.c

This PR switches skin_ghost_ranges from global to local, which fixes a segfault issue for running wedge BCs in parallel

Switch skin_ghost_ranges from global to local

---

README.md
core/zero/nccl_comm.c
gyrokinetic/creg/rt_gk_tcv_iwl_adapt_source_3x2v_p1.c

After running on perlmutter
```bash
srun -N 1 --ntasks=2 --gpus-per-task=1 --gpu-bind=closest compute-sanitizer --tool memcheck --leak-check full ./gkeyll_exec -M -g -e 2 -s 10 | tee memcheck_test.log
```
I discovered that the regression tests rt_gk_tcv_iwl_adapt_source_3x2v_p1 and rt_gk_tcv_sheath_3x2v_p1 are not compute-sanitizer clean. This leak is just due to a failure in releasing the communicator because the `nccl->has_deomp` is not always initialized. This branch fixes it.
Here is the kind of leak error that was popping :
```bash
========= Leaked 248,832 bytes at 0x7f78f1a00000
=========     Saved host backtrace up to driver entry point at allocation time
=========     Host Frame: [0x29220e]
=========                in /usr/lib64/libcuda.so.1
=========     Host …
```

compute-sanitizer is not clean for gk reg test (communicator release fails)

---

gyrokinetic/zero/rescale_ghost_jacf.c
gyrokinetic/zero/rescale_ghost_jacf_cu.cu

This is a micro fix of a warning occuring because the CPU compiler does not like to use a variable (even if the value is hardcoded) to initialize the size of an array.
the warnings are:
```bash
zero/rescale_ghost_jacf.c:73:32: warning: variable length array folded to constant array as an extension [-Wgnu-folding-constant]
73 |     double jacghost_surf_inv_c[num_basis_conf_surf];
|                                ^~~~~~~~~~~~~~~~~~~
zero/rescale_ghost_jacf.c:83:24: warning: variable length array folded to constant array as an extension [-Wgnu-folding-constant]
83 |       double jf_surf_c[num_basis_phase_surf];
|                        ^~~~~~~~~~~~~~~~~~~~
```
This PR simply put the hardcoded values directly in the array definitions instead of declaring it above through a variable. Also I …

Micro fix of a CPU warning: hardcoded variable for an array size

---

core/zero/nodal_ops.c

Addresses the bug in issue #839 . Thanks to @manauref for catching this.
modal to nodal and nodal to modal operations on surfaces are different for 1x simulations since there is no 0d basis. This commit addresses the issue and makes geometry fromfile work correctly for 1x. Below is the final potential from the gk_sheath_1x2v regression test run normally with mapc2p geometry and then with geometry fromfile.

1x Fromfile Fix

---

core/unit/ctest_mirror_grid_gen.c

According to #845, I was assigned to fix this unit test. It is fixed. The new geometry generators broke this unit test, but I'm surprised the previous commits passed. I had to input a corner nodal range into the geometry generators this time, as well as local and global.

Fix the core/unit/ctest_mirror_grid_gen.c
