ammarhakim/gkeyll

- apps/gkyl_app.h
- unit/ctest_update_fsm.c
- zero/gkyl_update_fsm.h
- zero/update_fsm.c
Refactoring of the update_fsm code to hook into the moment and vlasov apps
> Update FSM refactoring

- LICENSE
- apps/gkyl_vlasov.h
- apps/gkyl_vlasov_priv.h
- apps/vlasov.c
- apps/vm_field.c
- apps/vm_species.c
- regression/rt_euler_multiblock.c
- regression/rt_twostream.c
I need to merge this as it has been sitting around for too long. Not completed work but there is no point in keeping this in the branch for so long.
> Merging branch

- Makefile.sample
- zero/gkylzero.h
- zero/wave_geom.c
Merging this, so can rebranch for further fluid work.
> Updates to makefile, missing headers.

- apps/gkyl_vlasov.h
- apps/gkyl_vlasov_priv.h
- apps/vlasov.c
- apps/vm_fluid_species.c
- apps/vm_fluid_species_source.c
- apps/vm_species.c
- apps/vm_species_source.c
- Added a source for the VM fluid species.
- Source relies on a constant user-defined profile function, no current implementation of any dependence on boundary fluxes.
> VM fluid source

- Makefile
> Automatically generating gkylzero header at build time

- inf/Moments.lua
> CDIM is 3D and not 6D! Probably the cause for Mac crashes.

- apps/gkyl_moment.h
- apps/gkyl_moment_priv.h
- apps/gkyl_vlasov.h
- apps/mom_field.c
- apps/mom_species.c
- apps/moment.c
- apps/vlasov.c
- apps/vm_field.c
- apps/vm_species.c
- regression/rt_esshock.c
- regression/rt_vlasov_ot_5d.c
- regression/rt_vlasov_ot_6d.c
- unit/ctest_array.c
- zero/array_rio.c
- zero/dynvec.c
- zero/gkyl_elem_type_priv.h
- zero/mpi_comm.c
Fixed a number of bugs uncovered by unit tests. Also improved MPI communication. With the new system for a 5D VM problem we get only 20% or so degradation of weak-scaling performance on a 256x increase in number of cores.
> Fixed several bugs & MPI improvements

- inf/Moments.lua
Clearly this is not sustainable way of working.
> Fixed a problem with the Lua wrapping. This is just to do some test

- zero/range.c
- zero/rect_grid.c
It caused seg faults in g2. Please check g2 before making changes to core components in the future.
> Commenting out zeroing of range and rect_grid structs.

- zero/gkyl_fem_poisson.h
- zero/gkyl_fem_poisson_bctype.h
- zero/gkyl_fem_poisson_perp.h
the various Poisson solvers. No enum or structs or functions should be redefined!
> Adding common header for Poisson eqn BCs so they are shared between

- apps/vlasov.c
(underscore instead of hyphen for the moment).
> Make moment write out look more like G2 if doing G0 writing

- machines/configure.della-gpu.sh
- machines/mkdeps.della-gpu.sh
tested with g2-g0merge example file
> adding machine files for Princeton's della-gpu computer on g0

- zero/gkyl_mom_gyrokinetic_priv.h
@akashukla can you check if this fixes the issue you were seeing and merge if it does?
> Fix bug in gk mom private header. Seems benign but it appears it is not.

- apps/gkyl_vlasov.h
- apps/gkyl_vlasov_priv.h
- apps/vlasov.c
- apps/vm_species.c
For use in simulations with a time dependent forcing operator.
> Adding the option for the applied acceleration to be time dependent 

- Makefile
- configure
Added an install prefix to configure and Makefile. This still does not fix the problem Mana pointed out. This should be merged first and then Mana's PR reopened with these changes propagated into that branch first.
> Prefix fix

- apps/gk_field.c
- apps/gk_species.c
- apps/gkyl_app_priv.h
- apps/gkyl_gyrokinetic.h
- apps/gyrokinetic.c
- kernels/deflate_geo/deflate_geo_ser_p1.c
- kernels/deflate_geo/deflate_geo_ser_p2.c
- kernels/deflate_geo/gkyl_deflate_geo_kernels.h
- regression/rt_gk_mirror_1x2v_p1.c
- regression/rt_gk_mirror_3x2v_p1.c
- unit/ctest_gk_geometry.c
- zero/deflate_geo.c
- zero/gk_geometry.c
- zero/gk_geometry_cu.cu
- zero/gk_geometry_fromfile.c
- zero/gk_geometry_fromfile_cu.cu
- zero/gk_geometry_mapc2p.c
- zero/gk_geometry_tok.c
- zero/gk_geometry_tok_cu.cu
- zero/gkyl_deflate_geo.h
- zero/gkyl_deflate_geo_priv.h
- zero/gkyl_gk_geometry.h
G0 App can now do 1x2v mirror geometry using the world option to pass the psi value.
> 1x2v Mirror Test runs on cpu and gpu

- unit/ctest_proj_bimaxwellian_on_basis.c
- zero/gkyl_proj_bimaxwellian_on_basis.h
- zero/gkyl_proj_bimaxwellian_on_basis_priv.h
- zero/proj_bimaxwellian_on_basis.c
- zero/proj_bimaxwellian_on_basis_cu.cu
only implemented for gyrokinetics for now
> New object to project a bimaxwellian on basis

- kernels/gyrokinetic/bc_sheath_gyrokinetic_ser_p1.c
for the record, here's the corresponding gkylcas PR
https://github.com/ammarhakim/gkylcas/pull/34
> Slight update of 3x2v gk sheath kernel.

- unit/ctest_dynvec.c
- zero/dynvec.c
- zero/gkyl_dynvec.h
so had to do this for use in main. Will merge later into GK App branch
> Added a method to convert dynvector to array. Needed in some work and

- zero/bc_emission_spectrum.c
- zero/bc_emission_spectrum_cu.cu
- zero/gkyl_bc_emission_spectrum.h
- zero/gkyl_bc_emission_spectrum_priv.h
Boundary conditions for emitting walls for G2-G0. Accompanies pull request of the same name in G2.
> Emission spectrum BC

- zero/correct_mj.c
- zero/mj_moments.c
Changed:
- Fixed array operations (over gkyl_array_clear/accumulate to include "_range")
- Changed to an equivalent but more accurate way of computing "n", the fluid-stationary density, for the Maxwell-Juttner distribution.
> Touchup to MJ Density Moment 

- apps/gkyl_vlasov_priv.h
- apps/vlasov.c
- apps/vm_species.c
- apps/vm_species_bgk.c
- regression/rt_vlasov_bgk_relax_1x1v_p1.c
- regression/rt_vlasov_bgk_relax_1x1v_p2.c
- regression/rt_vlasov_bgk_relax_1x2v_p1.c
- regression/rt_vlasov_bgk_relax_1x2v_p2.c
- regression/rt_vlasov_bgk_relax_1x3v_p1.c
- regression/rt_vlasov_bgk_relax_1x3v_p2.c
- zero/bgk_collisions.c
- zero/bgk_collisions_cu.cu
Should help in debugging implicit collisions and be useful for relativistic simulations.
> Adding the BGK collision operator to the Vlasov app 

- apps/gk_species_projection.c
- regression/rt_gk_lbo_relax_1x2v_p1.c
Needed since we wish to evolve `jacobgeo*bmag*f`
> Add missing multiplication by bmag in GKYL_PROJ_FUNC of gk_species_projection

- apps/gyrokinetic.c
- cppcheck-suppress.txt
- run-cppcheck.sh
- zero/calc_metric.c
- zero/dg_iz.c
- zero/dg_recomb.c
- zero/math.c
There were some serious bugs in calc_metric (but probably not fatal). The calc_metric file is truly awful :) please someone take a look at this and help improve.
Deleted strange code in iz and recomb code.
Fixed output logging to not log with fp is 0.
> Fixing cppcheck errors.

- apps/gkyl_app.h
- apps/gkyl_gyrokinetic.h
- apps/gkyl_moment.h
- apps/gkyl_pkpm.h
- apps/gkyl_vlasov.h
- apps/gkyl_vlasov_priv.h
- apps/gyrokinetic_lw.c
- apps/vlasov.c
- apps/vlasov_lw.c
- apps/vm_species_lbo.c
- apps/zero_lw.c
- cppcheck-suppress.txt
- regression/xglua.c
- run-cppcheck.sh
- unit/ctest_rect_decomp.c
- unit/lua/test_RectDecomp.lua
- unit/lua/test_xglua.lua
- zero/array_rio.c
- zero/deflated_fem_poisson.c
- zero/gkyl_bc_sheath_gyrokinetic_priv.h
- zero/gkyl_calc_bmag_priv.h
- zero/gkyl_calc_derived_geo_priv.h
- zero/gkyl_dg_bin_ops_priv.h
- zero/gkyl_rect_decomp.h
- zero/rect_decomp.c
This brings in the hooks into MPI into G0 Lua-C layers. Vlasov Lua-C driver seems to work in parallel. Need to do more extensive testing that will be done after PR is merged in gk-g0-app.
Time to merge this into gk-g0-app. Plenty of minor and major fixes are also included.
> Hooks to MPI and MPI-ficaton of Vlasov App

- regression/rt_10m_lhdi_grad_closure.c
- unit/ctest_range.c
- unit/ctest_rect_decomp.c
- unit/mctest_mpi_comm.c
- zero/gkyl_range.h
- zero/gkyl_rect_decomp.h
- zero/mpi_comm.c
- zero/range.c
- zero/rect_decomp.c
- zero/wave_prop.c
Completed the corner syncs. This required a major refactor of sync code (periodic and non-periodic). I have not made the corresponding changes for nccl comm but these also need to be made.
> Corner syncs and mpi_comm refactor

- apps/gk_neut_species.c
- apps/gk_species.c
- apps/gkyl_app.h
- apps/gkyl_gyrokinetic.h
- apps/gkyl_gyrokinetic_priv.h
- apps/vm_species.c
- regression/rt_gk_lapd_cyl_3x2v_p1.c
- regression/rt_gk_mdpx_cart_3x2v_p1.c
- regression/rt_gk_mirror_3x2v_p1.c
- regression/rt_gk_step_out_2x2v_p1.c
- regression/rt_gk_wham_2x2v_p1.c
- zero/dg_updater_vlasov.c
- zero/gkyl_dg_updater_vlasov.h
Mostly symbolic PR (see commit message) but also to ask:
- Do you approve?
- Want me to rename this BC in moment/vlasov/pkpm apps too? it's just a `sed`
> Change meaning of GKYL_SPECIES_FIXED_FUNC BC option

- apps/gk_species_lbo.c
- apps/gkyl_gyrokinetic.h
- apps/vm_species_lbo.c
@JunoRavin I think there was a sqrt(2) missing in vm_lbo, can you confirm?
@akashukla I consolidated some normNu if-statements that I think you inserted/modified in the normNu refactor. Can you confirm this is ok?
Thanks
> small fixes in lbo apps

- zero/vlasov_lte_proj_on_basis_cu.cu
> Vlasov LTE CUDA function had a bug in it from the PR merge yesterday

- apps/block_geom.c
- apps/gkyl_app.h
- apps/gkyl_block_geom.h
- apps/gkyl_gyrokinetic_multib.h
- apps/gkyl_gyrokinetic_multib_priv.h
- apps/gyrokinetic_multib.c
- regression/rt_multib_euler_2d.c
- regression/rt_multib_step_2x2v_p1.c
- unit/ctest_block_geom.c
This is a shell of gyrokinetic multib app based directly on the multib moments app.
> Multib app gk

- apps/gyrokinetic.c
- regression/rt_gk_step_out_2x2v_p1.c
- regression/rt_multib_step_2x2v_p1.c
- unit/ctest_efit.c
- unit/ctest_step_compare.c
- zero/calc_metric.c
- zero/dg_rad_gyrokinetic_drag_cu.cu
- zero/efit.c
- zero/gk_geometry.c
- zero/gk_geometry_cu.cu
- zero/gk_geometry_mapc2p.c
- zero/gk_geometry_mirror.c
- zero/gk_geometry_tok.c
- zero/gkyl_calc_metric.h
- zero/gkyl_efit.h
- zero/gkyl_gk_geometry.h
- zero/gkyl_tok_geo.h
- zero/gkyl_tok_geo_priv.h
- zero/mirror_geo.c
- zero/tok_geo.c
- zero/tok_geo_utils.c
Merged in gap removal and also fixed mistakes in the 12 block regression test so it runs.
> Gap removal

- apps/gkyl_moment.h
- apps/gkyl_moment_priv.h
- apps/mom_coupling.c
- apps/mom_species.c
- apps/moment.c
- regression/rt_5m_elc_heat_flux.c
- regression/rt_5m_hartmann.c
- regression/rt_5m_ion_heat_flux.c
- regression/rt_iso_euler_hartmann.c
- zero/gkyl_moment_braginskii.h
- zero/gkyl_moment_non_ideal_priv.h
- zero/gkyl_sources_implicit.h
- zero/gkyl_wv_iso_euler.h
- zero/moment_braginskii.c
- zero/sources_implicit.c
- zero/wv_iso_euler.c
plus a bug fix for the 10 moment (since there is a fluid_rhs vector used now to potentially include transport terms into the implicit update, need to set this by hand for the 10 moment runs).
> Adding back in all the Braginskii work

- apps/gyrokinetic.c
> Fix bug in GK write_geo nodes writing

- apps/gk_field.c
- apps/gk_neut_species.c
- apps/gk_neut_species_react.c
- apps/gk_species.c
- apps/gk_species_bgk.c
- apps/gk_species_lbo.c
- apps/gk_species_react.c
- apps/gkyl_gyrokinetic_multib_priv.h
- apps/gkyl_gyrokinetic_priv.h
- apps/gyrokinetic.c
- apps/gyrokinetic_multib.c
- apps/multib_comm_conn_nccl.c
- unit/ctest_rescale_ghost_jacf.c
- zero/gk_geometry.c
- zero/gk_geometry_cu.cu
- zero/gk_geometry_mapc2p.c
- zero/gk_geometry_mirror.c
- zero/gk_geometry_tok.c
- zero/gkyl_gk_geometry.h
- zero/gkyl_rescale_ghost_jacf_priv.h
- zero/rescale_ghost_jacf_cu.cu
This is so that the MB GK app can call the separately to reduce bmag in between.
> Split contents of gyrokinetic_app_new into 2 methods

- apps/gk_field.c
Commit message:
The size of the polarization weight (times geo coeffs) epsilon in gk-field is the size of the global range in 1x sims, which interferes with the omega_H calculation in 1x when running in parallel. There was a confusing thing in that 1x epsilon is global but 2x/3x epsilon is local. Resolve this confusion by making epsilon also local in 1x and briefly creating a global epsilon which fem_parproj only needs during initialization. 1x and 2x sims produced expected results in parallel on my laptop (thanks to @akashukla for pointing this bug out).
> Fix the size of the polarization weight array in gk_field for 1x

- apps/gk_species.c
We didn't realize we messed up `is_zero_flux` passed to the collisionless solver in the static species PR #583. This commit fixes it.
:( we need automated testing.... :(
> Fix zero-flux BCs in GK solver

- apps/gk_species_bflux.c
- apps/gkyl_gyrokinetic.h
- apps/gkyl_gyrokinetic_priv.h
- apps/gyrokinetic.c
- apps/gyrokinetic_update_ssp_rk3.c
- regression/rt_gk_sheath_2x2v_p1.c
- regression/rt_gk_step_out_2x2v_p1.c
This is the implementation of DR #604 , merging into the gk-g0-app_energy_conservation-production branch.
> Boundary flux diagnostic API

- kernels/gyrokinetic/gkyl_mom_gyrokinetic_kernels.h
- kernels/gyrokinetic/gyrokinetic_int_mom_1x1v_ser_p1.c
- kernels/gyrokinetic/gyrokinetic_int_mom_1x1v_ser_p2.c
- kernels/gyrokinetic/gyrokinetic_int_mom_1x2v_ser_p1.c
- kernels/gyrokinetic/gyrokinetic_int_mom_1x2v_ser_p2.c
- kernels/gyrokinetic/gyrokinetic_int_mom_2x2v_ser_p1.c
- kernels/gyrokinetic/gyrokinetic_int_mom_2x2v_ser_p2.c
- kernels/gyrokinetic/gyrokinetic_int_mom_3x2v_ser_p1.c
- zero/gkyl_mom_gyrokinetic_priv.h
- zero/mom_gyrokinetic.c
- zero/mom_gyrokinetic_cu.cu
This small PR is adding additional kernels to compute individual integrated moments (M0, M1, M2). It is related to the gkylcas PR [67](https://github.com/ammarhakim/gkylcas/pull/67).
> Adding individual integrated moments kernels.

- apps/gk_species.c
- apps/gkyl_gyrokinetic.h
- apps/gkyl_gyrokinetic_priv.h
> Add ability to turn off GK collisionless terms

- unit/ctest_positivity_shift_gyrokinetic.c
> Fix use of moment calculating updater in GK pos shift test

- apps/gk_species_react.c
Check for ion species, so CX react rate gets written.
> Fix write function for reactions

- machines/configure.snellius-gpu.sh
- machines/jobScript.snellius-gpu.sh
- machines/mkdeps.snellius-gpu.sh
Added mkdeps and configuration scripts and an example jobscript for the Snellius supercomputer in the Netherlands.
PS This is my first time contributing to a project on Github, so if something went wrong or I'm not doing things by the book, please let me know so I do not make the same mistakes in the future.
> Install scripts for Snellius supercomputer

- zero/array_integrate_cu.cu
Running 
```
compute-sanitizer --tool memcheck --leak-check full ./cuda-build/unit/ctest_array_integrate
```
on Perlmutter gives a message like
```
=========     at gkyl_array_integrate_op_none_1x_ser_p1+0x330
=========     by thread (57,0,0) in block (0,0,0)
=========     Address 0x7f7640a003a0 is out of bounds
=========     and is 96 bytes before the nearest allocation at 0x7f7640a00400 of size 96 bytes
=========     Device Frame:void array_integrate_blockRedAtomic_cub<(unsigned int)256>(gkyl_array_integrate *, const gkyl_array *, double, const gkyl_array *, gkyl_range, gkyl_range, double *)+0x39d0
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x2f26ef]
=========                in /usr/lib64/libcuda.so.1
=========     Host …
```
> Protect against out-of-bounds access in reductions

- gyrokinetic/zero/radiation_read.c
> Small change to radiation_read file to eliminate error when trying to

- gyrokinetic/zero/bc_twistshift.c
- gyrokinetic/zero/gkyl_bc_twistshift_priv.h
doesn't change the core algorithm, just software changes to minimize code duplication and improve design.
Unit test continues to pass
> Software improvements to TS BC
